(deffacts parser-contents
          (open bind.clp)
          (open defclass.clp)
          (open defgeneric.clp)
          (open defglobal.clp)
          (open defmethod.clp)
          (open defmodule.clp)
          (open defrule.clp)
          (open deftemplate.clp)
          (open function.clp)
          (open lib.clp)
          (open optimize.clp)
          (open parser.clp)
          (open slots.clp)
          (open stages.clp)
          (open analysis/static/missing-comments.clp)
          (open analysis/static/salience-checks.clp)
          )
